services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./bd_data:/var/lib/mysql/mariadb
    container_name: c_mariadb

  monapache:
    image: httpd:latest
    volumes:
      - /var/www/html:/usr/local/apache2/htdocs  # Monte le répertoire local dans le conteneur
    ports:
      - 8088:80  # Mappe le port 8088 de l'hôte au port 80 du conteneur
    container_name: c_monapache

  monubuntu:
    image: ubuntu
    container_name: c_monubuntu

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8089:80
    container_name: c_monphpmyadmin
