version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./TP-info-411/sql:/docker-entrypoint-initdb.d
      - ./TP-info-411/bd_data:/var/lib/mysql
    container_name: c_mariadb

  monapache:
    image: httpd:latest
    ports:
      - 8088:80
    volumes:
      - ./TP-info-411/site:/var/www/html
    container_name: c_monapache

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8089:80
    container_name: c_monphpmyadmin
