version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./bd_data:/var/lib/mysql/mariadb
    container_name: c_mariadb

  monapache:
    image: php:8.3-apache  # Utilisation de l'image php:8.3-apache pour Apache + PHP
    volumes:
      - /var/www/html/sololeveling.info411.site/TP-info-411/site:/var/www/html  # Correction du répertoire source pour correspondre à /var/www/html dans l'image
    ports:
      - 8088:80  # Expose le port 8088 pour accéder à Apache via HTTP
    container_name: c_monapache

  monubuntu:
    image: ubuntu
    container_name: c_monubuntu

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8089:80
    container_name: c_monphpmyadmin
